title = "Guillermo Trenor"
baseURL = ""
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "G-Z0PW1GWL35"
enableRobotsTXT = true

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages]
[languages.en]
title = "Guillermo Trenor"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.es]
title = "Guillermo Trenor"
weight = 2
contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose an fitting and alignment style for the featured image using tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or size header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 2
math= true

[params.ananke.social.follow]
new_window_icon = false # show a little "opens in new window" icon next to the link
networks = [
  "linkedin",
  "github"
]

[params.ananke.social]
[params.ananke.social.linkedin]
username = "guillermo-trenor-navarro-2a18672ab"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.github]
username = "guitrena"
